feat: sign up form
GamblEats/GamblEats pull request #11
Opened 2022-12-16 15:02 UTC by Sachitto

2023-01-03 15:18 UTC, NathLeS requested changes

2023-01-03 15:18 UTC, NathLeS commented on front/components/AuthForm/styles.tsx
> +    width: 450px;
on a dit PAS DE PX

2023-01-03 15:18 UTC, NathLeS commented on front/components/AuthForm/styles.tsx
> +    width: 450px;
change moi TOUT ça

2023-01-03 15:18 UTC, NathLeS commented on front/components/AuthForm/styles.tsx
> +    width: 450px;
chien

2023-01-03 15:18 UTC, NathLeS commented on front/components/AuthForm/SignInForm.tsx
> +            console.log(values);
vas te faire foutre

2023-01-04 07:47 UTC, stivluc approved these changes

2023-01-04 07:47 UTC, merged